apiVersion: batch/v1
kind: Job
metadata:
  namespace: example02
  generateName: my-db-upgrade-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sh"
          - "-c"
          - "exit 1"
      restartPolicy: Never
  backoffLimit: 2    
